FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV USE_FIRESTORE_EMULATOR=true
ENV PORT=8000
ENV ENVIRONMENT=dev

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]