FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV USE_FIRESTORE_EMULATOR=false
ENV PORT=8080
ENV ENVIRONMENT=prod

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]