name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
       PROJECT_ID: ${{ secrets.PROJECT_ID }}
       REGION: ${{ secrets.REGION }}
       FIRESTORE_CREDENTIALS: ${{ secrets.FIRESTORE_CREDENTIALS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }} # Optional if you don't want to use the default, must create a key json to use.
          project_id: ${{ secrets.PROJECT_ID }}

      # --- Backend Deployment ---
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t gcr.io/$PROJECT_ID/backend ./backend -f ./backend/Dockerfile.prod
          docker push gcr.io/$PROJECT_ID/backend

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy backend \
          --image gcr.io/$PROJECT_ID/backend \
          --project $PROJECT_ID \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars "PROJECT_ID=$PROJECT_ID" \
          --set-secrets="FIRESTORE_CREDENTIALS=firestore-key:latest" \
          --port 8080

      # --- Frontend Deployment ---
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t gcr.io/$PROJECT_ID/frontend ./frontend -f ./frontend/Dockerfile.prod
          docker push gcr.io/$PROJECT_ID/frontend

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy frontend \
          --image gcr.io/$PROJECT_ID/frontend \
          --project $PROJECT_ID \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --port 3000